// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Ast from "../src/Ast.res.js";
import * as Nodetest from "node:test";
import * as Strict from "node:assert/strict";

Nodetest.test("pretty: Float literal", () => {
  Strict.strictEqual(Ast.pretty({
    TAG: "Literal",
    _0: {
      TAG: "Float",
      _0: 42.0
    }
  }), "42");
});

Nodetest.test("pretty: string literal", () => {
  Strict.strictEqual(Ast.pretty({
    TAG: "Literal",
    _0: {
      TAG: "String",
      _0: "hello"
    }
  }), "hello");
});

Nodetest.test("pretty: bool literals", () => {
  Strict.strictEqual(Ast.pretty({
    TAG: "Literal",
    _0: {
      TAG: "Bool",
      _0: true
    }
  }), "true");
  Strict.strictEqual(Ast.pretty({
    TAG: "Literal",
    _0: {
      TAG: "Bool",
      _0: false
    }
  }), "false");
});

Nodetest.test("pretty: null literal", () => {
  Strict.strictEqual(Ast.pretty({
    TAG: "Literal",
    _0: null
  }), "null");
});

Nodetest.test("pretty: unary negation", () => {
  Strict.strictEqual(Ast.pretty({
    TAG: "Unary",
    _0: "Negate",
    _1: {
      TAG: "Literal",
      _0: {
        TAG: "Float",
        _0: 5.0
      }
    }
  }), "(- 5)");
});

Nodetest.test("pretty: unary not", () => {
  Strict.strictEqual(Ast.pretty({
    TAG: "Unary",
    _0: "Exclamation",
    _1: {
      TAG: "Literal",
      _0: {
        TAG: "Bool",
        _0: true
      }
    }
  }), "(! true)");
});

Nodetest.test("pretty: binary add", () => {
  Strict.strictEqual(Ast.pretty({
    TAG: "Binary",
    _0: {
      TAG: "Literal",
      _0: {
        TAG: "Float",
        _0: 1.0
      }
    },
    _1: "Add",
    _2: {
      TAG: "Literal",
      _0: {
        TAG: "Float",
        _0: 2.0
      }
    }
  }), "(+ 1 2)");
});

Nodetest.test("pretty: all binary operators", () => {
  let cases = [
    [
      "Add",
      "+"
    ],
    [
      "Minus",
      "-"
    ],
    [
      "Multiply",
      "*"
    ],
    [
      "Divide",
      "/"
    ],
    [
      "Equal",
      "=="
    ],
    [
      "NotEqual",
      "!="
    ],
    [
      "LessThan",
      "<"
    ],
    [
      "LessThanOrEqual",
      "<="
    ],
    [
      "GreaterThan",
      ">"
    ],
    [
      "GreaterThanOrEqual",
      ">="
    ]
  ];
  cases.forEach(param => {
    Strict.strictEqual(Ast.pretty({
      TAG: "Binary",
      _0: {
        TAG: "Literal",
        _0: {
          TAG: "Float",
          _0: 1.0
        }
      },
      _1: param[0],
      _2: {
        TAG: "Literal",
        _0: {
          TAG: "Float",
          _0: 2.0
        }
      }
    }), `(` + param[1] + ` 1 2)`);
  });
});

Nodetest.test("pretty: grouping", () => {
  Strict.strictEqual(Ast.pretty({
    TAG: "Grouping",
    _0: {
      TAG: "Literal",
      _0: {
        TAG: "Float",
        _0: 7.0
      }
    }
  }), "(group 7)");
});

Nodetest.test("pretty: nested expression from book", () => {
  Strict.strictEqual(Ast.pretty({
    TAG: "Grouping",
    _0: {
      TAG: "Unary",
      _0: "Negate",
      _1: {
        TAG: "Binary",
        _0: {
          TAG: "Literal",
          _0: {
            TAG: "Float",
            _0: 5.0
          }
        },
        _1: "Add",
        _2: {
          TAG: "Literal",
          _0: {
            TAG: "Float",
            _0: 2.0
          }
        }
      }
    }
  }), "(group (- (+ 5 2)))");
});

Nodetest.test("pretty: precedence is unambiguous", () => {
  Strict.strictEqual(Ast.pretty({
    TAG: "Binary",
    _0: {
      TAG: "Binary",
      _0: {
        TAG: "Literal",
        _0: {
          TAG: "Float",
          _0: 1.0
        }
      },
      _1: "Add",
      _2: {
        TAG: "Literal",
        _0: {
          TAG: "Float",
          _0: 2.0
        }
      }
    },
    _1: "Multiply",
    _2: {
      TAG: "Literal",
      _0: {
        TAG: "Float",
        _0: 3.0
      }
    }
  }), "(* (+ 1 2) 3)");
  Strict.strictEqual(Ast.pretty({
    TAG: "Binary",
    _0: {
      TAG: "Literal",
      _0: {
        TAG: "Float",
        _0: 1.0
      }
    },
    _1: "Minus",
    _2: {
      TAG: "Binary",
      _0: {
        TAG: "Literal",
        _0: {
          TAG: "Float",
          _0: 2.0
        }
      },
      _1: "Minus",
      _2: {
        TAG: "Literal",
        _0: {
          TAG: "Float",
          _0: 3.0
        }
      }
    }
  }), "(- 1 (- 2 3))");
});

/*  Not a pure module */
