// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Ast from "../src/Ast.res.js";
import * as Parser from "../src/Parser.res.js";
import * as Scanner from "../src/Scanner.res.js";
import * as Nodetest from "node:test";
import * as Stdlib_Result from "@rescript/runtime/lib/es6/Stdlib_Result.js";
import * as Strict from "node:assert/strict";

function parseToSexpr(source) {
  let tokens = Scanner.scanTokens(Scanner.make(source));
  return Stdlib_Result.map(Parser.parse(tokens), Ast.pretty);
}

function assertParses(source, expected) {
  let s = parseToSexpr(source);
  if (s.TAG === "Ok") {
    Strict.strictEqual(s._0, expected);
    return;
  }
  Strict.strictEqual(`error: ` + s._0.message, expected);
}

Nodetest.test("parse: integer literal", () => assertParses("42", "42"));

Nodetest.test("parse: addition", () => assertParses("1 + 2", "(+ 1 2)"));

Nodetest.test("parse: precedence — * binds tighter than +", () => assertParses("1 + 2 * 3", "(+ 1 (* 2 3))"));

Nodetest.test("parse: left-associativity of +", () => assertParses("1 + 2 + 3", "(+ (+ 1 2) 3)"));

Nodetest.test("parse: unary negation", () => assertParses("-5", "(- 5)"));

Nodetest.test("parse: unary applied to grouped expression", () => assertParses("-(5 + 2)", "(- (group (+ 5 2)))"));

Nodetest.test("parse: comparison and equality", () => assertParses("1 < 2 == true", "(== (< 1 2) true)"));

Nodetest.test("parse: parenthesized expression", () => assertParses("(1 + 2) * 3", "(* (group (+ 1 2)) 3)"));

Nodetest.test("parse: error on missing right paren", () => {
  let s = parseToSexpr("(1 + 2");
  if (s.TAG === "Ok") {
    Strict.strictEqual(`unexpected ok: ` + s._0, "error");
    return;
  }
  Strict.strictEqual(s._0.message, "Expect ')' after expression.");
});

Nodetest.test("parse: error on bare operator", () => {
  let s = parseToSexpr("+ 1");
  if (s.TAG === "Ok") {
    Strict.strictEqual(`unexpected ok: ` + s._0, "error");
    return;
  }
  Strict.strictEqual(s._0.message, "Expected expression.");
});

export {
  parseToSexpr,
  assertParses,
}
/*  Not a pure module */
