// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Bool from "@rescript/runtime/lib/es6/Stdlib_Bool.js";

function pretty(expr) {
  switch (expr.TAG) {
    case "Literal" :
      let n = expr._0;
      if (n === null) {
        return "null";
      }
      switch (n.TAG) {
        case "Float" :
          return String(n._0);
        case "String" :
          return n._0;
        case "Bool" :
          return Stdlib_Bool.toString(n._0);
      }
    case "Unary" :
      return parenthesize(unaryPretty(expr._0), [expr._1]);
    case "Binary" :
      return parenthesize(binaryPretty(expr._1), [
        expr._0,
        expr._2
      ]);
    case "Grouping" :
      return parenthesize("group", [expr._0]);
  }
}

function parenthesize(name, exprs) {
  return `(` + name + ` ` + exprs.map(pretty).join(" ") + `)`;
}

function unaryPretty(unary) {
  if (unary === "Negate") {
    return "-";
  } else {
    return "!";
  }
}

function binaryPretty(binary) {
  switch (binary) {
    case "Add" :
      return "+";
    case "Minus" :
      return "-";
    case "Multiply" :
      return "*";
    case "Divide" :
      return "/";
    case "Equal" :
      return "==";
    case "NotEqual" :
      return "!=";
    case "LessThan" :
      return "<";
    case "LessThanOrEqual" :
      return "<=";
    case "GreaterThan" :
      return ">";
    case "GreaterThanOrEqual" :
      return ">=";
  }
}

export {
  pretty,
  parenthesize,
  unaryPretty,
  binaryPretty,
}
/* No side effect */
