// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Fs from "fs";
import * as Js_array from "rescript/lib/es6/js_array.js";
import * as Readline from "readline";
import * as Pervasives from "rescript/lib/es6/pervasives.js";

function readFileByLine(path) {
  var lines = [];
  var rl = Readline.createInterface({
        input: Fs.createReadStream(path),
        crlfDelay: Pervasives.infinity
      });
  return new Promise((function (resolve, reject) {
                rl.on("close", (function (param) {
                        rl.close();
                        resolve(lines);
                      }));
                rl.on("error", (function (err) {
                        reject(err);
                      }));
                rl.on("line", (function (line) {
                        lines.push(line);
                      }));
              }));
}

function runFile(path) {
  readFileByLine(path).then(function (lines) {
          return Promise.resolve(Js_array.joinWith("\n", lines));
        }).then(function (msg) {
        console.log(msg);
        return Promise.resolve(undefined);
      });
}

function run(source) {
  console.log("Scanner: " + source + "");
}

runFile("./example.lox");

export {
  readFileByLine ,
  runFile ,
  run ,
}
/*  Not a pure module */
