// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Scanner from "./Scanner.res.js";
import * as Nodefs from "node:fs";
import * as Process from "process";
import * as Pervasives from "@rescript/runtime/lib/es6/Pervasives.js";
import * as Nodereadline from "node:readline";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function readFileByLine(path) {
  let lines = [];
  let rl = Nodereadline.createInterface({
    input: Nodefs.createReadStream(path),
    crlfDelay: Pervasives.infinity
  });
  return new Promise((resolve, reject) => {
    rl.on("close", param => {
      rl.close();
      resolve(lines);
    });
    rl.on("error", err => reject(err));
    rl.on("line", line => {
      lines.push(line);
    });
  });
}

function run(source) {
  let tokens = Scanner.scanTokens(Scanner.make(source));
  console.log(tokens.map(Scanner.tokenToString));
}

function runFile(path) {
  readFileByLine(path).then(lines => Promise.resolve(lines.join("\n"))).then(code => {
    if (code.length > 0) {
      run(code);
    }
    return Promise.resolve();
  });
}

function runPrompt() {
  let rl = Nodereadline.createInterface({
    input: Process.stdin,
    output: Primitive_option.some(Process.stdout),
    prompt: "> ",
    crlfDelay: Pervasives.infinity
  });
  rl.prompt(null);
  rl.on("line", code => {
    if (code.length > 0) {
      run(code);
    }
    rl.prompt(null);
  });
}

runPrompt();

let Log;

export {
  Log,
  readFileByLine,
  run,
  runFile,
  runPrompt,
}
/*  Not a pure module */
