// Generated by ReScript, PLEASE EDIT WITH CARE


var hadError = {
  contents: false
};

function report(line, where, message) {
  console.log("[line " + line + "] Error\"" + where + "\": \" " + message + "");
  hadError.contents = true;
}

function error(line, message) {
  report(line, "", message);
}

export {
  hadError ,
  report ,
  error ,
}
/* No side effect */
