// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_List from "@rescript/runtime/lib/es6/Stdlib_List.js";
import * as Stdlib_Result from "@rescript/runtime/lib/es6/Stdlib_Result.js";

function errorAtHead(tokens, message) {
  if (tokens !== 0) {
    return {
      message: message,
      line: tokens.hd.line
    };
  } else {
    return {
      message: message,
      line: 0
    };
  }
}

function consume(tokens, expected, message) {
  if (tokens === 0) {
    return {
      TAG: "Error",
      _0: errorAtHead(tokens, message)
    };
  }
  let t = tokens.hd;
  if (t.tokenType === expected) {
    return {
      TAG: "Ok",
      _0: [
        t,
        tokens.tl
      ]
    };
  } else {
    return {
      TAG: "Error",
      _0: errorAtHead(tokens, message)
    };
  }
}

function toBinaryOp(tt) {
  switch (tt) {
    case "Minus" :
      return "Minus";
    case "Plus" :
      return "Add";
    case "Slash" :
      return "Divide";
    case "Star" :
      return "Multiply";
    case "BangEqual" :
      return "NotEqual";
    case "EqualEqual" :
      return "Equal";
    case "Greater" :
      return "GreaterThan";
    case "GreaterEqual" :
      return "GreaterThanOrEqual";
    case "Less" :
      return "LessThan";
    case "LessEqual" :
      return "LessThanOrEqual";
    default:
      return;
  }
}

function toUnaryOp(tt) {
  switch (tt) {
    case "Minus" :
      return "Negate";
    case "Bang" :
      return "Exclamation";
    default:
      return;
  }
}

function parseLeftAssoc(tokens, ops, nextRule) {
  let loop = (left, tokens) => {
    if (tokens === 0) {
      return {
        TAG: "Ok",
        _0: [
          left,
          tokens
        ]
      };
    }
    let t = tokens.hd;
    if (!ops.includes(t.tokenType)) {
      return {
        TAG: "Ok",
        _0: [
          left,
          tokens
        ]
      };
    }
    let op = toBinaryOp(t.tokenType);
    if (op !== undefined) {
      return Stdlib_Result.flatMap(nextRule(tokens.tl), param => loop({
        TAG: "Binary",
        _0: left,
        _1: op,
        _2: param[0]
      }, param[1]));
    } else {
      return {
        TAG: "Error",
        _0: {
          message: "Unexpected operator.",
          line: t.line
        }
      };
    }
  };
  return Stdlib_Result.flatMap(nextRule(tokens), param => loop(param[0], param[1]));
}

function term(tokens) {
  return parseLeftAssoc(tokens, [
    "Plus",
    "Minus"
  ], factor);
}

function comparison(tokens) {
  return parseLeftAssoc(tokens, [
    "Greater",
    "GreaterEqual",
    "Less",
    "LessEqual"
  ], term);
}

function unary(tokens) {
  if (tokens === 0) {
    return {
      TAG: "Error",
      _0: {
        message: "Expected expression.",
        line: 0
      }
    };
  }
  let op = toUnaryOp(tokens.hd.tokenType);
  if (op !== undefined) {
    return Stdlib_Result.map(unary(tokens.tl), param => [
      {
        TAG: "Unary",
        _0: op,
        _1: param[0]
      },
      param[1]
    ]);
  } else {
    return primary(tokens);
  }
}

function primary(tokens) {
  if (tokens === 0) {
    return {
      TAG: "Error",
      _0: {
        message: "Expected expression.",
        line: 0
      }
    };
  }
  let rest = tokens.tl;
  let t = tokens.hd;
  let match = t.tokenType;
  switch (match) {
    case "LeftParen" :
      return Stdlib_Result.flatMap(equality(rest), param => {
        let inner = param[0];
        return Stdlib_Result.map(consume(param[1], "RightParen", "Expect ')' after expression."), param => [
          {
            TAG: "Grouping",
            _0: inner
          },
          param[1]
        ]);
      });
    case "String" :
      let s = t.literal;
      if (typeof s !== "object" || s.TAG !== "LoxString") {
        return {
          TAG: "Error",
          _0: {
            message: "String token missing string literal.",
            line: t.line
          }
        };
      } else {
        return {
          TAG: "Ok",
          _0: [
            {
              TAG: "Literal",
              _0: {
                TAG: "String",
                _0: s._0
              }
            },
            rest
          ]
        };
      }
    case "Number" :
      let n = t.literal;
      if (typeof n !== "object") {
        return {
          TAG: "Error",
          _0: {
            message: "Number token missing numeric literal.",
            line: t.line
          }
        };
      }
      switch (n.TAG) {
        case "LoxInt" :
        case "LoxNumber" :
          return {
            TAG: "Ok",
            _0: [
              {
                TAG: "Literal",
                _0: {
                  TAG: "Float",
                  _0: n._0
                }
              },
              rest
            ]
          };
        default:
          return {
            TAG: "Error",
            _0: {
              message: "Number token missing numeric literal.",
              line: t.line
            }
          };
      }
    case "False" :
      return {
        TAG: "Ok",
        _0: [
          {
            TAG: "Literal",
            _0: {
              TAG: "Bool",
              _0: false
            }
          },
          rest
        ]
      };
    case "Nil" :
      return {
        TAG: "Ok",
        _0: [
          {
            TAG: "Literal",
            _0: null
          },
          rest
        ]
      };
    case "True" :
      return {
        TAG: "Ok",
        _0: [
          {
            TAG: "Literal",
            _0: {
              TAG: "Bool",
              _0: true
            }
          },
          rest
        ]
      };
    default:
      return {
        TAG: "Error",
        _0: {
          message: "Expected expression.",
          line: t.line
        }
      };
  }
}

function equality(tokens) {
  return parseLeftAssoc(tokens, [
    "BangEqual",
    "EqualEqual"
  ], comparison);
}

function factor(tokens) {
  return parseLeftAssoc(tokens, [
    "Star",
    "Slash"
  ], unary);
}

let expression = equality;

function parse(tokens) {
  return Stdlib_Result.map(equality(Stdlib_List.fromArray(tokens)), param => param[0]);
}

export {
  errorAtHead,
  consume,
  toBinaryOp,
  toUnaryOp,
  expression,
  equality,
  comparison,
  term,
  factor,
  unary,
  primary,
  parseLeftAssoc,
  parse,
}
/* No side effect */
