// Generated by ReScript, PLEASE EDIT WITH CARE

import * as LoxError from "./loxError.res.js";

let Value = {};

let keywords = [
  [
    "and",
    "And"
  ],
  [
    "class",
    "Class"
  ],
  [
    "else",
    "Else"
  ],
  [
    "false",
    "False"
  ],
  [
    "fun",
    "Fun"
  ],
  [
    "for",
    "For"
  ],
  [
    "if",
    "If"
  ],
  [
    "nil",
    "Nil"
  ],
  [
    "or",
    "Or"
  ],
  [
    "print",
    "Print"
  ],
  [
    "return",
    "Return"
  ],
  [
    "super",
    "Super"
  ],
  [
    "this",
    "This"
  ],
  [
    "true",
    "True"
  ],
  [
    "var",
    "Var"
  ],
  [
    "while",
    "While"
  ]
];

function make(source) {
  return {
    source: source,
    tokens: [],
    start: 0,
    current: 0,
    line: 1
  };
}

function isAtEnd(param) {
  return param.current >= param.source.length;
}

function isDigit(c) {
  if (c >= "0") {
    return c <= "9";
  } else {
    return false;
  }
}

function isAlpha(c) {
  if (c >= "a" && c <= "z" || c >= "A" && c <= "Z") {
    return true;
  } else {
    return c === "_";
  }
}

function isAlphaNumeric(c) {
  if (isAlpha(c)) {
    return true;
  } else {
    return isDigit(c);
  }
}

function advanceScanner(scanner) {
  return {
    source: scanner.source,
    tokens: scanner.tokens,
    start: scanner.start,
    current: scanner.current + 1 | 0,
    line: scanner.line
  };
}

function getChar(param) {
  let current = param.current;
  let source = param.source;
  if (current > source.length) {
    return;
  } else {
    return source.charAt(current - 1 | 0);
  }
}

function getLexeme(param) {
  return param.source.substring(param.start, param.current);
}

function peek(scanner) {
  if (isAtEnd(scanner)) {
    return "\0";
  } else {
    return scanner.source.charAt(scanner.current);
  }
}

function peekNext(scanner) {
  if ((scanner.current + 1 | 0) >= scanner.source.length) {
    return "\0";
  } else {
    return scanner.source.charAt(scanner.current + 1 | 0);
  }
}

function addToken(scanner, tokenType) {
  return {
    source: scanner.source,
    tokens: scanner.tokens.concat([{
        tokenType: tokenType,
        lexeme: getLexeme(scanner),
        literal: "LoxNil",
        line: scanner.line
      }]),
    start: scanner.start,
    current: scanner.current,
    line: scanner.line
  };
}

function addTokenWithLiteral(scanner, tokenType, literal) {
  return {
    source: scanner.source,
    tokens: scanner.tokens.concat([{
        tokenType: tokenType,
        lexeme: getLexeme(scanner),
        literal: literal,
        line: scanner.line
      }]),
    start: scanner.start,
    current: scanner.current,
    line: scanner.line
  };
}

function addDoubleToken(scanner, doubleToken, singleToken) {
  let match = getChar(advanceScanner(scanner));
  if (match === "=") {
    return addToken(advanceScanner(scanner), doubleToken);
  } else {
    return addToken(scanner, singleToken);
  }
}

function addCommentToken(scanner) {
  let match = getChar(advanceScanner(scanner));
  if (match === "/") {
    let _scanner = scanner;
    while (true) {
      let scanner$1 = _scanner;
      if (peek(scanner$1) === "\n" || isAtEnd(scanner$1)) {
        return scanner$1;
      }
      _scanner = advanceScanner(scanner$1);
      continue;
    };
  } else {
    return addToken(scanner, "Slash");
  }
}

function addStringToken(scanner) {
  let consumeString = _scanner => {
    while (true) {
      let scanner = _scanner;
      if (peek(scanner) === "\"" || isAtEnd(scanner)) {
        return scanner;
      }
      if (peek(scanner) !== "\n") {
        _scanner = advanceScanner({
          source: scanner.source,
          tokens: scanner.tokens,
          start: scanner.start,
          current: scanner.current,
          line: scanner.line + 1 | 0
        });
        continue;
      }
      _scanner = advanceScanner(scanner);
      continue;
    };
  };
  let scanner$1 = consumeString(scanner);
  if (isAtEnd(scanner$1)) {
    LoxError.error(String(scanner$1.line), "Unterminated string.");
    return scanner$1;
  }
  let scanner$2 = advanceScanner(scanner$1);
  let literal = {
    TAG: "LoxString",
    _0: scanner$2.source.substring(scanner$2.start + 1 | 0, scanner$2.current - 1 | 0)
  };
  return addTokenWithLiteral(scanner$2, "String", literal);
}

function addNumberToken(scanner) {
  let consumeNumber = _scanner => {
    while (true) {
      let scanner = _scanner;
      if (isDigit(peek(scanner))) {
        _scanner = advanceScanner(scanner);
        continue;
      }
      if (!(peek(scanner) === "." && isDigit(peekNext(scanner)))) {
        return scanner;
      }
      _scanner = advanceScanner(scanner);
      continue;
    };
  };
  let scanner$1 = consumeNumber(scanner);
  return addToken(scanner$1, "Number");
}

function addIdentifierToken(scanner) {
  let consumeIdentifier = _scanner => {
    while (true) {
      let scanner = _scanner;
      if (!isAlphaNumeric(peek(scanner))) {
        return scanner;
      }
      _scanner = advanceScanner(scanner);
      continue;
    };
  };
  let scanner$1 = consumeIdentifier(scanner);
  let text = scanner$1.source.substring(scanner$1.start, scanner$1.current);
  let match = keywords.find(param => param[0] === text);
  let token = match !== undefined ? match[1] : "Identifier";
  return addToken(scanner$1, token);
}

function scanToken(scanner) {
  let scanner$1 = advanceScanner(scanner);
  let c = getChar(scanner$1);
  if (c === undefined) {
    return scanner$1;
  }
  switch (c) {
    case "!" :
      return addDoubleToken(scanner$1, "BangEqual", "Bang");
    case "(" :
      return addToken(scanner$1, "LeftParen");
    case ")" :
      return addToken(scanner$1, "RightParen");
    case "*" :
      return addToken(scanner$1, "Star");
    case "+" :
      return addToken(scanner$1, "Plus");
    case "," :
      return addToken(scanner$1, "Comma");
    case "-" :
      return addToken(scanner$1, "Minus");
    case "." :
      return addToken(scanner$1, "Dot");
    case "/" :
      return addCommentToken(scanner$1);
    case ";" :
      return addToken(scanner$1, "Semicolon");
    case "<" :
      return addDoubleToken(scanner$1, "LessEqual", "Less");
    case "=" :
      return addDoubleToken(scanner$1, "EqualEqual", "Equal");
    case ">" :
      return addDoubleToken(scanner$1, "GreaterEqual", "Greater");
    case "\"" :
      return addStringToken(scanner$1);
    case "\n" :
      return {
        source: scanner$1.source,
        tokens: scanner$1.tokens,
        start: scanner$1.start,
        current: scanner$1.current,
        line: scanner$1.line + 1 | 0
      };
    case " " :
    case "\r" :
    case "\t" :
      return scanner$1;
    case "{" :
      return addToken(scanner$1, "LeftBrace");
    case "}" :
      return addToken(scanner$1, "RightBrace");
    default:
      if (isDigit(c)) {
        return addNumberToken(scanner$1);
      } else if (isAlpha(c)) {
        return addIdentifierToken(scanner$1);
      } else {
        LoxError.error(String(scanner$1.line), "Unexpected character.");
        return scanner$1;
      }
  }
}

function scanTokens(_scanner) {
  while (true) {
    let scanner = _scanner;
    if (isAtEnd(scanner)) {
      let token_line = scanner.line;
      let token = {
        tokenType: "Eof",
        lexeme: "",
        literal: "LoxNil",
        line: token_line
      };
      return scanner.tokens.concat([token]);
    }
    let scanner_source = scanner.source;
    let scanner_tokens = scanner.tokens;
    let scanner_start = scanner.current;
    let scanner_current = scanner.current;
    let scanner_line = scanner.line;
    let scanner$1 = {
      source: scanner_source,
      tokens: scanner_tokens,
      start: scanner_start,
      current: scanner_current,
      line: scanner_line
    };
    _scanner = scanToken(scanner$1);
    continue;
  };
}

function tokenTypeToString(tokenType) {
  switch (tokenType) {
    case "LeftParen" :
      return "LeftParen";
    case "RightParen" :
      return "RightParen";
    case "LeftBrace" :
      return "LeftBrace";
    case "RightBrace" :
      return "RightBrace";
    case "Comma" :
      return "Comma";
    case "Dot" :
      return "Dot";
    case "Minus" :
      return "Minus";
    case "Plus" :
      return "Plus";
    case "Semicolon" :
      return "Semicolon";
    case "Slash" :
      return "Slash";
    case "Star" :
      return "Star";
    case "Bang" :
      return "Bang";
    case "BangEqual" :
      return "BangEqual";
    case "Equal" :
      return "Equal";
    case "EqualEqual" :
      return "EqualEqual";
    case "Greater" :
      return "Greater";
    case "GreaterEqual" :
      return "GreaterEqual";
    case "Less" :
      return "Less";
    case "LessEqual" :
      return "LessEqual";
    case "Identifier" :
      return "Identifier";
    case "String" :
      return "String";
    case "Number" :
      return "Number";
    case "And" :
      return "And";
    case "Class" :
      return "Class";
    case "Else" :
      return "Else";
    case "False" :
      return "False";
    case "Fun" :
      return "Fun";
    case "For" :
      return "For";
    case "If" :
      return "If";
    case "Nil" :
      return "Nil";
    case "Or" :
      return "Or";
    case "Print" :
      return "Print";
    case "Return" :
      return "Return";
    case "Super" :
      return "Super";
    case "This" :
      return "This";
    case "True" :
      return "True";
    case "Var" :
      return "Var";
    case "While" :
      return "While";
    case "Eof" :
      return "Eof";
  }
}

function tokenToString(token) {
  return tokenTypeToString(token.tokenType) + ", " + token.lexeme + ", " + String(token.literal);
}

export {
  Value,
  keywords,
  make,
  isAtEnd,
  isDigit,
  isAlpha,
  isAlphaNumeric,
  advanceScanner,
  getChar,
  getLexeme,
  peek,
  peekNext,
  addToken,
  addTokenWithLiteral,
  addDoubleToken,
  addCommentToken,
  addStringToken,
  addNumberToken,
  addIdentifierToken,
  scanToken,
  scanTokens,
  tokenTypeToString,
  tokenToString,
}
/* No side effect */
